workflows:
  version: 2
  test:
    jobs:
      - test-3.11
      - test-latest
  cron:
    triggers:
      - schedule:
          cron: "10 5 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - test-3.11
      - test-latest
jobs:
  test-3.11: &test-template
    docker:
      - image: circleci/python:3.11
    environment:
      PYTHON_VERSION=3.11
    working_directory: ~/repo
    steps:
      - checkout

      - run:
          name: Write Python version to file
          command: |
            echo $PYTHON_VERSION > /tmp/PYTHON_VERSION
            cat /tmp/PYTHON_VERSION

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}-{{ checksum "/tmp/PYTHON_VERSION" }}
      - run:
          name: Install dependencies
          command: |
            python -m venv venv || virtualenv -p /usr/bin/python2.7 venv
            . venv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}-{{ checksum "/tmp/PYTHON_VERSION" }}

      - run:
          name: Run test suite
          command: |
            . venv/bin/activate
            python test_data.py
  test-latest:
    <<: *test-template
    docker:
      - image: circleci/python:latest
    environment:
      PYTHON_VERSION=latest
