name: CI

on:
  push:
  schedule:
    - cron: "10 5 * * *"

jobs:
  build:
    name: Test
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Pip install
        run: pip install -r requirements.txt
      - name: Run tests
        run: python test_data.py
